### ISSUE TITLE
tracker for dep manifest file detection and coverage for mozilla-central / mozilla/gecko-dev

### ISSUE THREAD

**Issue by g-k** [mozilla-services/find-package-rugaru#114]
node.js npm:

- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&path=package-lock.json
- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&path=package.json

node.js / yarn:

- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&path=yarn.lock

rust:

- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&path=Cargo.toml
- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&path=Cargo.lock

python: 

- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&regexp=false&path=requirements*.txt
- [ ] https://searchfox.org/mozilla-central/search?q=&case=true&regexp=false&path=requirements*.in
- [ ] possibly more?
