### ISSUE TITLE
GH Meta: improve logging

### ISSUE THREAD

**Issue by g-k** [mozilla-services/find-package-rugaru#120]
add the following fields to relevant logs:

- [x] org repo
- [x] worker name 
- [x] page N of resource name w/ after params
- [x] `<page result size>` of total for each paged resource
- [x] an ID
- [ ] perf / timing metrics (from RawResult)? (punting for now)
